### ISSUE TITLE
Doctests fail under --no-default-features (FileSigner examples aren't feature-gated)

### ISSUE THREAD

**Issue by r-near** [r-near/near-kit-rs#257]
`cargo test -p near-kit --doc --no-default-features` fails with 3 doctest compile errors — all examples that use `FileSigner` unconditionally, which doesn't exist without the `file-signer` feature:

- `src/client/signer.rs` — `RotatingSigner` type docs (line ~687)
- `src/client/signer.rs` — `RotatingSigner::from_signers` (line ~767)
- `src/lib.rs` — the signers section example (line ~298)

```
error[E0432]: unresolved import `near_kit::FileSigner`
```

Pre-existing (not introduced by #256; CI only runs doctests with default features, so nothing is red today). Purely a hygiene issue for anyone running the doctest suite with features off.

Options, roughly in order of preference:
1. Rewrite the three examples around `InMemorySigner`/`EnvSigner` and mention `FileSigner` in prose only
2. Split the `FileSigner` lines into a separate ` ```rust,ignore ` block
3. Conditional doc inclusion via `cfg_attr(feature = "file-signer", doc = ...)` (works but ugly)

Low priority.
